# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰for opening your very first issue in this project. AnitaB.org is an inclusive community, committed to creating a safe and positive environment.ğŸŒ¸ Please adhere to our [Code of Conduct](https://github.com/anitab-org/portal/blob/develop/code_of_conduct.md).ğŸ™Œ
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/anitab-org/portal/blob/develop/PULL_REQUEST_TEMPLATE.md) and [Commit Guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide)! 

  If you want to report a bugğŸ please follow our [Issue Template](https://github.com/anitab-org/portal/blob/develop/ISSUE_TEMPLATE.md). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  
  
  Feel free to join us on [AnitaB.org Open Source Zulip Community](https://anitab-org.zulipchat.com/).ğŸ’– We have different streams for each active repository for discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request âœ¨.Make sure that you have followed the [Commit Guidelines](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide), else your PR may not pass the Commit Messages check.

  AnitaB.org is an inclusive community, committed to creating a safe and positive environment.ğŸŒ¸Please adhere to our [Code of Conduct](https://github.com/anitab-org/portal/blob/develop/code_of_conduct.md) and [Contribution Guidelines](https://github.com/anitab-org/portal/blob/develop/CONTRIBUTING.md).ğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  Feel free to join us on [AnitaB.org Open Source Zulip Community](https://anitab-org.zulipchat.com/).ğŸ’– We have different streams for each active repository for discussions.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.