language: python
python:
  - "3.4"
install:
  - "pip install -r requirements/dev.txt"
  - pip install coveralls==0.4.4
env:
  secure: "MU+x68snHYqrm/aYHgdJcutZoTiRo1sl4MU8K09GfMp/Y4s6McNllqLheg8hM6MZAlQcOTPyp/kE8nr8cneYExl0tvH4yU6gVIZj9C7oOYJm4Qx++uNRlevbQ2Yo1lkHZnL8iNlXvqsOzxrB9ryxNClyc/M4OS6fQuyXzYcC/Fg="
before_script:
  - psql -c "CREATE DATABASE systersdb;" -U postgres
script:
  - coverage run systers_portal/manage.py test --settings=systers_portal.settings.testing
  - flake8 systers_portal
notifications:
  irc:
    channels: "irc.freenode.org#systers-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c403378d624b2391961e
    on_success: change
    on_failure: always
    on_start: false
after_success:
  coveralls --rcfile=.coveragerc
