sudo: false
language: python
python:
  - "3.6"
install:
  - "pip install -r requirements/dev.txt"
  - pip install coveralls==0.4.4
before_script:
  - export SECRET_KEY=foobarbaz
  - psql -c "CREATE DATABASE systersdb;" -U postgres
script:
  - coverage run systers_portal/manage.py test --settings=systers_portal.settings.testing
  - flake8 systers_portal
notifications:
  irc:
    channels: "irc.freenode.org#systers-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c403378d624b2391961e
    on_success: change
    on_failure: always
    on_start: false
after_success:
  coveralls --rcfile=.coveragerc
