sudo: true
language: python
env:
  - MOZ_HEADLESS=1

addons:
  firefox: "55.0"

services:
  - postgresql

python:
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzvf geckodriver-v0.20.1-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
install:
  - "pip install -r requirements/dev.txt"
  - pip install coveralls==0.4.4
  - sudo apt-get install python-gdal
before_script:
  - export GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
  - export SECRET_KEY=foobarbaz
#  - curl -o ipdb.tar.gz https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz
#  - tar -xzf ipdb.tar.gz -C systers_portal/
  - psql -c "CREATE DATABASE systersdb;" -U postgres
script:
  - coverage run systers_portal/manage.py test --settings=systers_portal.settings.testing
  - flake8 systers_portal
notifications:
  irc:
    channels: "irc.freenode.org#systers-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c403378d624b2391961e
    on_success: change
    on_failure: always
    on_start: false
after_success:
  coveralls --rcfile=.coveragerc
